eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#   server:
#     enableSelfPreservation: false
#     renewalPercentThreshold: 0.55
     
        
server:
  port: 8761
                                               
   
#spring:
#  application:
#    name: Eureka